set nocompatible
filetype plugin indent on

set autoindent
" allow backspacing over everything in insert mode
set backspace=indent,eol,start
" Set to auto read when a file is changed from the outside
set autoread

syntax on
set nu
set nowrap
set nobackup
" foldmethod
set fdm=syntax

" Tab strategy
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set hidden             " Hide buffers when they are abandoned

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" Jump between windows
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Use shortcut <\-cd> to cd current file's directory
nnoremap <leader>cd :cd %:h<CR>

iab xdate <c-r>=strftime("%d/%m/%Y %H:%M:%S")<cr>
iab xfname <c-r>=expand("%:t")<cr>
iab xhead <c-o>:r ~/.vim/xhead.txt<cr>

set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set wildmenu
set statusline=2

" guioptions
" remove toolbar
set guioptions-=T
" remove menubar
set guioptions-=m

" Use Q for formatting
"nnoremap Q gq
